name: Node Build.

on: [push]

jobs:
  mainbuild:
    runs-on: ${{ matrix.os }}

  strategy:
    matrix:
      node-version: [20.x]
      os: [windows.latest]
    
  steps:
    - uses: actions/checkout@v1
    - name: Run node.js on latest windows.
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install NPM  and build.
      run: | 
        npm ci
        npm run build
    